### ISSUE TITLE
> and >> break the formatting

### ISSUE THREAD

**Issue by bbugh** [pzavolinsky/atom-language-elmx#2]
When putting a `>` or `>>` anywhere in an `.elmx` file, the formatting will break until matching an `elmx-tag-open`. Both of these examples will break the formatting:

``` elm
-- example 1
fake' = 5 > 5
-- example 2
((Maybe.withDefault fallback) >> succeed)

--- ... elm code in this area will not be formatted

<div> -- it will start here again
```

The problem is in `elmx-tag-content`. If I remove it, the grammar works fine. It is simply matching any `>` and considering it to be tag content, which is not the case outside of the JSX grammar.

I spent a bit of time on attempting to fix it, but I'm not very familiar with the grammar rules. It seems like the best solution is to only match `elmx-tag-content` if it's between an `elmx-tag-open` and `elmx-tag-close`, however I could not find a solution that worked in all cases.

**Comment by pzavolinsky** [comment]
Hi @bbugh , thanks for the detailed report. 

Those TextMate grammars are truly painful to debug.

I'll give it a try and see if I can figure it out. I'll compare it with the grammar in the `react` atom package and see if that one is working better.

Cheers!

**Comment by bbugh** [comment]
Good call, here's the two standard jsx packages:

[language-javascript-jsx](https://github.com/subtleGradient/language-javascript-jsx/blob/master/grammars/JavaScript%20with%20JSX.cson#L196) - This looks as I suspected, that it needs to match the whole tag section, and then match sub patterns for the different parts. It's a bit different from your pattern set up but I see enough similarities that you might be able to make more sense of it. 😎

There's also the [https://github.com/gandm/language-babel/blob/master/grammars/Babel%20Language.json](the Babel grammar) but it's _much_ more complex.

Thanks so much for putting together all of these JSX for Elm libraries, it's very helpful. Elm's current default way of writing HTML and CSS is unbearable.

**Comment by pzavolinsky** [comment]
Here is a third one (the one I originally used to create the Elmx one): [atom-react](https://github.com/orktes/atom-react/blob/master/grammars/JavaScript%20%28JSX%29.cson) 

(this one used to be much much simpler when I first used it).

> Thanks so much for putting together all of these JSX for Elm libraries, it's very helpful. Elm's current default way of writing HTML and CSS is unbearable. 

Cool, thanks, I'm glad you find it useful!

**Comment by pzavolinsky** [comment]
Hey @bbugh , I've just pushed version `1.2.4` with a surgical fix to the grammar.

It was more [hocus pocus regex dark magic](https://manual.macromates.com/en/regular_expressions#syntax_oniguruma) (_shy look-behind_?!)  than an actual conscientious though process so hopefully it won't break other scenarios.

Let me know if it's working for you and we can close the issue (btw, you might need to <kbd>View</kbd> -> <kbd>Reload</kbd>).

Cheers!

**Comment by bbugh** [comment]
Looks great. I notice it still breaks if there's no whitespace (shy look-behind, what a thing), but that's not "proper" elm syntax anyway so I don't think it's a big deal. Thanks for the quick fix!

**Comment by pzavolinsky** [comment]
Agreed, saw that `5>` coming, but it's not worth fixing it with a ton of regex, unless we get enough complaints about it.

I'm closing this issue.

Thanks for reporting it, let me know if you find anything else.

Cheers.
